Another rewrite - Remove usage of grep and sed, only use awk - Make script posix conform

diff --git a/gandi-update b/gandi-update
--- a/gandi-update
+++ b/gandi-update
@@ -1,18 +1,17 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 #
-# This script updates a zone record using the API of Gandi.net 
-# (http://doc.livedns.gandi.net/) and notifies by mail upon errors. 
+# A small, even minimalistic, simple and posix compliant script to update a
+# zone record using the API of Gandi.net (http://doc.livedns.gandi.net/).
+#
+# Requirements: A posix shell, the command "curl" and "find" (from 
+# package "findutils"). For notifications, you need a working "sendmail" 
+# command.
 # Ideally, this script runs as a cronjob or systemd.timer unit. If the zone 
 # record doesn't exist yet, it gets created.
-#
-# Create a configuration file under /etc/default/gandi-updat containing the
+# Create a configuration file under /etc/default/gandi-update containing the
 # mandatory variables APIKEY, RECORD and DOMAIN. Adapt the other variables 
-# to your needs.
-# Set DNS_SERVER to query the current IP address of a host from a specific 
-# DNS server.
-# Set UPDATE_MSG to get a notification upon a successful update.
-# The packages "curl" and "coreutils" are required. A "host" command (for 
-# example from "bind9-utils package) is required aswell.
+# to your needs. Set UPDATE_MSG to get a notification upon a successful 
+# update.
 #
 # Mandatory variables:
 #RECORD="www"
@@ -22,12 +21,11 @@
 #MAIL="notification-email@address"
 #UPDATE_MSG="IP updated for $FQDN." # Message to send upon IP update.
 #TIMEOUT="5"
-#DNS_SERVER="9.9.9.9"
 #TTL="300"
 #API="https://api.gandi.net/v5/livedns/"
-#IP_SERVICE="https://ifconfig.co/"
+#IP_SERVICE="https://ifconfig.co"
 
-set -euo pipefail
+set -eu
 
 # Get and set variables
 . "/etc/default/gandi-update"
@@ -36,12 +34,9 @@ DOMAIN=${DOMAIN:-}
 APIKEY=${APIKEY:-}
 MAIL=${MAIL:-$(whoami)}
 UPDATE_MSG=${UPDATE_MSG:-}
-DNS_SERVER=${DNS_SERVER:-}
 TTL=${TTL:-300}
-TIMEOUT=${TIMEOUT:-5}
 API=${API:-https://api.gandi.net/v5/livedns/}
 IP_SERVICE=${IP_SERVICE:-https://ifconfig.co}
-SENDMAIL=${SENDMAIL:-/usr/sbin/sendmail}
 SILENT="${SILENT:-false}"
 FORCE_UPDATE_DAYS="${FORCE_UPDATE_DAYS:-1}"
 DISABLE_IPV6=${DISABLE_IPV6:-false}
@@ -49,92 +44,91 @@ DISABLE_IPV6=${DISABLE_IPV6:-false}
 # Script variables
 SCRIPTNAME=$(basename "$0")
 HOSTNAME=$(hostname --long)
-LC_ALL=C # Speed up grep
-
-# Lockfile, not running as systemd service
-if [[ "active" != $(systemctl is-active gandi-update.timer) ]]; then
-	LOCKFILE="/tmp/$SCRIPTNAME-lockfile"
-    exec {FD}<>"$LOCKFILE" || exit 1
-    flock -n "$FD" || { echo "[$SCRIPTNAME] Already running." >&2; exit 1; }
-    # Be silent, we are probabley running on a cronjob, only print errors.
-    SILENT="${SILENT:-true}"
-fi
 
 # Check mandatory variables
-[[ -z "$RECORD" ]] && echo "No domain set." && exit 1
-[[ -z "$DOMAIN" ]] && echo "No record set." && exit 1
-[[ -z "$APIKEY" ]] && echo "No apikey set." && exit 1
+[ -z "$RECORD" ] && echo "No domain set." && exit 1
+[ -z "$DOMAIN" ] && echo "No record set." && exit 1
+[ -z "$APIKEY" ] && echo "No apikey set." && exit 1
+! command -v curl >/dev/null && echo "No curl available." && exit 1
+! command -v find >/dev/null && echo "No find available." && exit 1
 
 # Curl args
-CURL_ARGS="-m $TIMEOUT"
-[[ "$SILENT" == "true" ]] && CURL_ARGS="$CURL_ARGS --silent --output /dev/null"
+CURL_ARGS="--max-timeout 5"
+[ "$SILENT" = "true" ] && CURL_ARGS="$CURL_ARGS --silent --output /dev/null"
 
 # Function variables
-if [[ "$RECORD" == "@" ]]; then
+if [ "$RECORD" = "@" ]; then
 	FQDN="$DOMAIN"
 else
 	FQDN="${RECORD}"."${DOMAIN}"
 fi
 CACHE_FILE="/tmp/$SCRIPTNAME-$(echo "$FQDN" | tr -cd '[:alnum:]')"
+NL="
+"
 
 run() {
 	UPDATED="false"
 	ERROR=""
-	IP_VERSIONS=(4 6)
-	[[ "$DISABLE_IPV6" != "false" ]] && IP_VERSIONS=(4)
-	for VER in "${IP_VERSIONS[@]}"; do
-		if [[ "$VER" == "4" ]]; then
-			REGEXP='[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
+	IP_VERSIONS="4 6"
+	[ "$DISABLE_IPV6" != "false" ] && IP_VERSIONS="4"
+
+	if [ "active" != "$(systemctl is-active gandi-update.timer)" ]; then
+		SILENT="${SILENT:-true}"
+	fi
+	
+	for VER in $IP_VERSIONS; do
+		if [ "$VER" = "4" ]; then
+			AWK_IP_PATTERN='{match($0,/[0-9]{1,3}+\.[0-9]{1,3}+\.[0-9]{1,3}+\.[0-9]{1,3}+/); ip = substr($0,RSTART,RLENGTH); print ip}'
 			TYPE="A"
 			IP="" && IP_DNS=""
-		elif [[ "$VER" == "6" ]]; then
-			REGEXP='([a-f0-9:]+:+)+[a-f0-9]+'
+		elif [ "$VER" = "6" ]; then
+			AWK_IP_PATTERN='{match($0,/([a-f0-9:]+:+)+[a-f0-9]+/); ip = substr($0,RSTART,RLENGTH); print ip}'
 			TYPE="AAAA"
 			IP="" && IP_DNS=""
 		fi
 		if get_public_ip; then
-			[[ $SILENT != "false"  ]] || echo "My public IPv$VER address is $IP."
+			[ "$SILENT" != "false"  ] || echo "My public IPv$VER address is $IP."
 			if resolve_ip; then
-				[[ $SILENT != "false"  ]] || echo "The host $FQDN is resolving to $IP_DNS."
+				[ "$SILENT" != "false"  ] || echo "The host $FQDN is resolving to $IP_DNS."
 				if cache_ip; then
 					if get_record; then
 						if update_ip; then
-							[[ $SILENT != "false"  ]] || echo "Updated $FQDN to IPv$VER address $IP." && UPDATED="true"
+							[ "$SILENT" != "false"  ] || echo "Updated $FQDN to IPv$VER address $IP." && UPDATED="true"
 						else
-							ERROR+="Could not update IPv$VER address for $FQDN to $IP."$'\n'
+							ERROR="Could not update IPv$VER address for $FQDN to $IP.$NL$ERROR"
 						fi
 					else
 						if create_record; then
-							[[ $SILENT != "false" ]] || echo "Created DNS entry for $FQDN with IPv$VER address $IP."
+							[ "$SILENT" != "false" ] || echo "Created DNS entry for $FQDN with IPv$VER address $IP."
 						else
-							ERROR+="Could not create DNS entry for $FQDN with IPv$VER $IP."$'\n'
+							ERROR="Could not create DNS entry for $FQDN with IPv$VER $IP.$NL$ERROR"
 						fi
 					fi
 				else
-					[[ $SILENT != "false" ]] || echo "No IPv$VER update needed for host $FQDN."
+					[ "$SILENT" != "false" ] || echo "No IPv$VER update needed for host $FQDN."
 				fi
 			else
-				ERROR+="Could not resolve IPv$VER address of $FQDN."$'\n'
+				ERROR="Could not resolve IPv$VER address of $FQDN.$NL$ERROR"
 			fi
 		else
-			ERROR+="Could not get public IPv$VER address from $IP_SERVICE."$'\n'
+			ERROR="Could not get public IPv$VER address from $IP_SERVICE.$NL$ERROR"
 		fi
 	done
 	notify
 }
 
 get_public_ip() {
-	IP=$(curl -s -"$VER" "$IP_SERVICE" | grep -oE "$REGEXP" | head -1) || return 1
+	IP=$(curl -s -"$VER" "$IP_SERVICE" | awk "$AWK_IP_PATTERN" ) && [ -n "$IP" ] || return 1
 }
 
 resolve_ip() {
-	IP_DNS=$(host -W "$TIMEOUT" "$FQDN" $DNS_SERVER | grep -oE "$REGEXP" | head -1) || return 1
+	IP_DNS=$(getent ahostsv"$VER" "$FQDN" | awk '{ print $1; exit }') || return 1
 }
 
 cache_ip() {
-	[[ -f "$CACHE_FILE"-"$VER" ]] && find "$CACHE_FILE-$VER" -type f -mtime +"$FORCE_UPDATE_DAYS" -delete
-	[[ ! -f "$CACHE_FILE"-"$VER" ]] && echo "$IP" > "$CACHE_FILE"-"$VER"
-	if [[ "$(cat "$CACHE_FILE"-"$VER")" != "$IP" || "$IP_DNS" != "$IP" ]]; then
+	[ -f "$CACHE_FILE"-"$VER" ] && find "$CACHE_FILE-$VER" -type f -mtime +"$FORCE_UPDATE_DAYS" -delete
+	[ ! -f "$CACHE_FILE"-"$VER" ] && echo "$IP" > "$CACHE_FILE"-"$VER"
+	if [ "$(cat "$CACHE_FILE"-"$VER")" != "$IP" ] || [ "$IP_DNS" != "$IP" ]; then
 		echo "$IP" > "$CACHE_FILE"-"$VER"
 	else
 		return 1
@@ -144,8 +138,9 @@ cache_ip() {
 get_record() {
 	RECORD_CHECK=$(curl -s -H 'Content-Type: application/json' \
 		-H "Authorization: Apikey $APIKEY" \
-		"$API/domains/$DOMAIN/records/$RECORD/$TYPE")
-	echo "$RECORD_CHECK" | grep -q "\"rrset_name\":\"$RECORD\"" || return 1
+		"$API/domains/$DOMAIN/records/$RECORD/$TYPE" | 
+		awk 'match($0, /"rrset_name":"[a-z]+/){print substr($0, RSTART+14,  RLENGTH-14)}')
+	[ "$RECORD_CHECK" = "$RECORD" ] || return 1
 }
 
 create_record() {
@@ -171,11 +166,11 @@ update_ip() {
 }
 
 notify() {
-	[[ -n "$ERROR" ]] && echo "$ERROR"
-	if [[ -n "$MAIL" && -x "$SENDMAIL" && -n "$ERROR" ]]; then
-		echo -e "To: $MAIL\nSubject: [$SCRIPTNAME] IP address error for $FQDN on $HOSTNAME\n\n$ERROR" | "$SENDMAIL" -t
-	elif [[ "$UPDATED" != "false" && -n "$UPDATE_MSG" ]]; then
-		echo -e "To: $MAIL\nSubject: [$SCRIPTNAME] IP address updated for $FQDN on $HOSTNAME\n\n$UPDATE_MSG" | "$SENDMAIL" -t
+	[ -n "$ERROR" ] && echo "$ERROR"
+	if [ -n "$MAIL" ] && command -v sendmail > /dev/null && [ -n "$ERROR" ]; then
+		echo "To: $MAIL${NL}Subject: [$SCRIPTNAME] IP address error for $FQDN on $HOSTNAME$NL$NL$ERROR" | sendmail -t
+	elif [ "$UPDATED" != "false" ] && [ -n "$UPDATE_MSG" ]; then
+		echo "To: $MAIL${NL}Subject: [$SCRIPTNAME] IP address updated for $FQDN on $HOSTNAME$NL$NL$UPDATE_MSG" | sendmail -t
 	fi
 }
 
